# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CFG' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CFG
  pod 'Firebase/Auth'
  pod 'Firebase/Core’

  target 'CFGTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CFGUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
